<ul class="recent-posts services unstyled">
  <li class="recent-posts_li post-1935 services type-services status-publish has-post-thumbnail hentry list-item-0 clearfix item_1">
    <figure class="thumbnail featured-thumbnail"><a href="http://suryahospitals.com/staging/services-view/outpatient-services/" title="Outpatient Services"><img src="http://suryahospitals.com/staging/wp-content/uploads/2014/03/icon_01-1.png" alt="Outpatient Services"></a></figure>
    <h5><a href="http://suryahospitals.com/staging/services-view/outpatient-services/" title="Outpatient Services">Outpatient Services</a></h5>
    <div class="clear"></div>
	<p>Not all health issues require hospitalisation. But there are still numerous minor health concerns for which you may need to consult a super-specialty hospital. At Surya, we offer a range of outpatient services for women and children with health issues that require advanced diagnostics, consultation and treatment but without the need for getting admitted. All you need to do is pick up the phone and call to book an appointment, or simply walk in to Surya's OPD for any medical need.</p>
	<!--<div class="slider_text_droppdown OUTPATIENT_SERVICES_dd">
		<h1>Apollo Clinics</h1>
		<p>Apollo Clinics extend its reach providing world class healthcare wherever you are</p>
		<div class="sld_cols">
			<div class="sld_single_col">
                <div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
            </div>
			<div class="sld_single_col">
            	<div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
            </div>
            <div class="sld_single_col">
            	<div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
                <div><a href="#">Link 1</a></div>
            </div>
		</div>
    </div>-->
  </li>
  <li class="recent-posts_li post-1933 services type-services status-publish has-post-thumbnail hentry list-item-1 clearfix item_2">
    <figure class="thumbnail featured-thumbnail"><a href="http://suryahospitals.com/staging/services-view/inpatient-services/" title="Inpatient Services"><img src="http://suryahospitals.com/staging/wp-content/uploads/2014/03/icon_02-1.png" alt="Inpatient Services"></a></figure>
    <h5><a href="http://suryahospitals.com/staging/services-view/inpatient-services/" title="Inpatient Services">Inpatient Services</a></h5>
    <div class="clear"></div>
    	<div class="slider_text_droppdown">
    	<p>When it comes to health issues that require hospitalisation for diagnostic, therapeutic procedure, close monitoring and care during treatment and recovery period, you won’t find any services better than Surya’s unparalleled Inpatient Services with one of the most expansive and sophisticated setup in women and children care in the country. Infants, children, parents and women who come to us seeking super-specialty care find themselves cared and reassured in the most comprehensive manner under our wide range general and intensive care units and super sub-specialties.</p>
        <p>Surya's 105 bedded tertiary care unit in neonatal care is the largest setup in India. Apart from doctors specialised in neonatal care, the nursing staff at Surya’s NICU unit are trained specifically for the job. From saving the smallest neonate to the sickest baby, Surya’s committed staff has earned many credentials along the way, and continues to set new benchmarks when it comes to ensuring survival of extremely premature babies.</p>
    </div>
  </li>
  <li class="recent-posts_li post-1931 services type-services status-publish has-post-thumbnail hentry list-item-2 clearfix item_3">
    <figure class="thumbnail featured-thumbnail"><a href="http://suryahospitals.com/staging/services-view/emergency-unit/" title="Emergency Unit"><img src="http://suryahospitals.com/staging/wp-content/uploads/2014/03/icon_03-1.png" alt="Emergency Unit"></a></figure>
    <h5><a href="http://suryahospitals.com/staging/services-view/emergency-unit/" title="Emergency Unit">Emergency Unit</a></h5>
    <div class="clear"></div>
    	<div class="slider_text_droppdown">
    	<p>Surya Hospital's frontline emergency services not only set us a class above other healthcare setups, but also makes us industry benchmarks with some unmatched features like:</p>
        <p>Apart from the state-of-the-art Operation Theatres and Intensive Care Units like NICU, PICU and Adult ICU, we at Surya Hospitals offer unique emergency support through our well-thought about services.</p>
		<p>Most of the ambulances available in the city are equipped to handle adult patients, with bigger bed, stretcher and equipments to handle adult emergencies. When it comes to neonates and paediatric patients, their needs are different. Being a speciality healthcare hospital for neonates and children, we understand their needs better.</p>
    </div>
  </li>
  <li class="recent-posts_li post-1929 services type-services status-publish has-post-thumbnail hentry list-item-3 clearfix item_4">
    <figure class="thumbnail featured-thumbnail"><a href="http://suryahospitals.com/staging/services-view/neonatal-i-c-u/" title="N.I.C.U. &amp; P.I.C.U."><img src="http://suryahospitals.com/staging/wp-content/uploads/2014/03/icon_04-1.png" alt="N.I.C.U. &amp; P.I.C.U."></a></figure>
    <h5><a href="http://suryahospitals.com/staging/services-view/neonatal-i-c-u/" title="N.I.C.U. &amp; P.I.C.U.">N.I.C.U. &amp; P.I.C.U.</a></h5>
    <div class="clear"></div>
    	<div class="slider_text_droppdown">
    	<p>An infant less than 28 days of age is called neonate or newborn. During neonatal period, rapid physiological changes and many critical events can occur. Some ‘neonates’ who are born prematurely (born before 37 completed weeks of gestation), or babies who require resuscitation at birth, babies having respiratory distress, or babies with heart failure or other health issues; or those in whom birth defects may be noticed, need extra medical care and special support. These babies are then admitted to Neonatal Intensive Care Unit (NICU).</p>
        <p>At Surya, we understand the special needs of these babies and provide them best medical care from our neonatal and paediatric super-specialists as well as support from the best of technology. Combining the best of experts and technology, Surya’s NICU Unit has been largely successful in achieving higher survival rates and lowest complication rates that are comparable with the best in the world. Our unit has successfully looked after premature baby as premature as 23 weeks and as small as 460 grams. The survival rate for extremely premature infant at Surya is one of the best in country.</p>
    </div>
  </li>
  <li class="recent-posts_li post-1925 services type-services status-publish has-post-thumbnail hentry list-item-4 clearfix item_5">
    <figure class="thumbnail featured-thumbnail"><a href="http://suryahospitals.com/staging/services-view/adult-critical-care/" title="Women Care"><img src="http://suryahospitals.com/staging/wp-content/uploads/2014/03/icon_07-1.png" alt="Women Care"></a></figure>
    <h5><a href="http://suryahospitals.com/staging/services-view/adult-critical-care/" title="Women Care">Women Care</a></h5>
    <div class="clear"></div>
    	<div class="slider_text_droppdown">
    	<p>Surya's Adult ICU facility is an advanced state-of-the-art diagnostic, surgical and treatment setup for women suffering serious complications arising from pregnancy, or various other vital organ diseases.</p>
        <p>Our intensivists and nursing staff are available 24x7 to handle medical crisis arising from</p>
		<div class="sld_cols">
			<div class="sld_single_col">
                <div><a href="#">Respiratory illnesses</a></div>
                <div><a href="#">Non-interventional cardiology</a></div>
                <div><a href="#">Kidney diseases</a></div>
            </div>
			<div class="sld_single_col">
				<div><a href="#">Neurological diseases</a></div>
            	<div><a href="#">High-risk surgical cases</a></div>
                <div><a href="#">High-risk pregnancies</a></div>
            </div>
		</div>
    </div>
  </li>
  <li class="recent-posts_li post-1927 services type-services status-publish has-post-thumbnail hentry list-item-5 clearfix item_6">
    <figure class="thumbnail featured-thumbnail"><a href="http://suryahospitals.com/staging/services-view/endoscopy/" title="ENDOSCOPY CENTER"><img src="http://suryahospitals.com/staging/wp-content/uploads/2014/03/icon_08.png" alt="ENDOSCOPY CENTER"></a></figure>
    <h5><a href="http://suryahospitals.com/staging/services-view/endoscopy/" title="ENDOSCOPY CENTER">ENDOSCOPY CENTER</a></h5>
    <div class="clear"></div>
    	<div class="slider_text_droppdown">
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tincidunt leo a dolor iaculis tincidunt. Pellentesque eu lacus sodales, porttitor quam sit amet, venenatis sapien. Praesent sodales metus eu est eleifend varius. Integer lorem magna, cursus ac pharetra luctus, auctor nec mi. Duis in auctor metus. Pellentesque aliquam, elit sed venenatis semper, lorem elit pellentesque nisl, vitae pretium diam nulla at urna. Curabitur tortor dolor, sagittis eget nulla non, dignissim consequat leo. Duis nulla mauris, sodales id ex vel, accumsan malesuada velit. Nulla facilisi. Duis cursus lacus et odio facilisis, non cursus ipsum congue. Sed suscipit, turpis a euismod maximus, nulla urna condimentum sem, eleifend tempus urna elit vitae felis. Morbi id laoreet velit, vel laoreet mi. Nullam vestibulum accumsan tortor.</p>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc at dui a arcu dictum mattis in quis neque. Vivamus sit amet eros pharetra, pretium felis quis, ultrices ex. Integer at nulla iaculis, mollis ex quis, aliquet sapien. Maecenas vitae elementum velit. Etiam id odio eget diam hendrerit vehicula eu sed risus. Aenean vel lobortis eros. In purus elit, mollis sit amet volutpat id, finibus nec turpis. Maecenas faucibus congue faucibus. Duis ac eros vel dui suscipit mollis. Curabitur nec eros ex. Duis metus est, vulputate at est ac, commodo volutpat turpis. Praesent eget tristique nisi.</p>
    </div>
  </li>
  <li class="recent-posts_li post-1923 services type-services status-publish has-post-thumbnail hentry list-item-6 clearfix item_7">
    <figure class="thumbnail featured-thumbnail"><a href="http://suryahospitals.com/staging/services-view/diagnostics/" title="Diagnostics"><img src="http://suryahospitals.com/staging/wp-content/uploads/2014/03/icon_06-1.png" alt="Diagnostics"></a></figure>
    <h5><a href="http://suryahospitals.com/staging/services-view/diagnostics/" title="Diagnostics">Diagnostics</a></h5>
    <div class="clear"></div>
    	<div class="slider_text_droppdown">
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tincidunt leo a dolor iaculis tincidunt. Pellentesque eu lacus sodales, porttitor quam sit amet, venenatis sapien. Praesent sodales metus eu est eleifend varius. Integer lorem magna, cursus ac pharetra luctus, auctor nec mi. Duis in auctor metus. Pellentesque aliquam, elit sed venenatis semper, lorem elit pellentesque nisl, vitae pretium diam nulla at urna. Curabitur tortor dolor, sagittis eget nulla non, dignissim consequat leo. Duis nulla mauris, sodales id ex vel, accumsan malesuada velit. Nulla facilisi. Duis cursus lacus et odio facilisis, non cursus ipsum congue. Sed suscipit, turpis a euismod maximus, nulla urna condimentum sem, eleifend tempus urna elit vitae felis. Morbi id laoreet velit, vel laoreet mi. Nullam vestibulum accumsan tortor.</p>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc at dui a arcu dictum mattis in quis neque. Vivamus sit amet eros pharetra, pretium felis quis, ultrices ex. Integer at nulla iaculis, mollis ex quis, aliquet sapien. Maecenas vitae elementum velit. Etiam id odio eget diam hendrerit vehicula eu sed risus. Aenean vel lobortis eros. In purus elit, mollis sit amet volutpat id, finibus nec turpis. Maecenas faucibus congue faucibus. Duis ac eros vel dui suscipit mollis. Curabitur nec eros ex. Duis metus est, vulputate at est ac, commodo volutpat turpis. Praesent eget tristique nisi.</p>
    </div>
  </li>
  <li class="recent-posts_li post-4972 services type-services status-publish has-post-thumbnail hentry list-item-7 clearfix item_8"><figure class="thumbnail featured-thumbnail"><a href="http://suryahospitals.com/staging/services-view/school-programme/" title="School Programme"><img src="http://suryahospitals.com/staging/wp-content/uploads/2014/03/icon_08.png" alt="School Programme"></a></figure><h5><a href="http://suryahospitals.com/staging/services-view/school-programme/" title="School Programme">School Programme</a></h5><div class="clear"></div>
		<div class="slider_text_droppdown">
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tincidunt leo a dolor iaculis tincidunt. Pellentesque eu lacus sodales, porttitor quam sit amet, venenatis sapien. Praesent sodales metus eu est eleifend varius. Integer lorem magna, cursus ac pharetra luctus, auctor nec mi. Duis in auctor metus. Pellentesque aliquam, elit sed venenatis semper, lorem elit pellentesque nisl, vitae pretium diam nulla at urna. Curabitur tortor dolor, sagittis eget nulla non, dignissim consequat leo. Duis nulla mauris, sodales id ex vel, accumsan malesuada velit. Nulla facilisi. Duis cursus lacus et odio facilisis, non cursus ipsum congue. Sed suscipit, turpis a euismod maximus, nulla urna condimentum sem, eleifend tempus urna elit vitae felis. Morbi id laoreet velit, vel laoreet mi. Nullam vestibulum accumsan tortor.</p>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc at dui a arcu dictum mattis in quis neque. Vivamus sit amet eros pharetra, pretium felis quis, ultrices ex. Integer at nulla iaculis, mollis ex quis, aliquet sapien. Maecenas vitae elementum velit. Etiam id odio eget diam hendrerit vehicula eu sed risus. Aenean vel lobortis eros. In purus elit, mollis sit amet volutpat id, finibus nec turpis. Maecenas faucibus congue faucibus. Duis ac eros vel dui suscipit mollis. Curabitur nec eros ex. Duis metus est, vulputate at est ac, commodo volutpat turpis. Praesent eget tristique nisi.</p>
    </div>
	</li>
</ul>